### ISSUE TITLE
Search/Filter List of Trips

### ISSUE THREAD

**Issue by silicaRich** [CodePathTeam8/sightseeing-app#10]
User can search for a trip by specifying a query and launching a search. Search displays a list of results.
 User can see picture, trip name, distance.

**Comment by silicaRich** [comment]
@Oneill38 will take this task

**Comment by silicaRich** [comment]
Need categories / filter items doesnt have to look like this but its inspiration!
![image](https://cloud.githubusercontent.com/assets/1787212/18072004/6b8859c0-6e28-11e6-9186-dd289eefaa1a.png)

**Comment by Oneill38** [comment]
Basic search filters work. Can for sure be iterated on but it's up and running
