### ISSUE TITLE
[Android Bootcamp] Team Project - Group 8 : Second Walkthrough is ready for review

### ISSUE THREAD

**Issue by silicaRich** [CodePathTeam8/sightseeing-app#11]
Please review /cc @codepathreview @codepath. This is second walkthrough of our app with functionality added. 

http://i.imgur.com/t2VJ9vk.gif

**Comment by codepathreview** [comment]
:+1: Nice work so far on the group project. Your team has made great progress in the last week. Hope you are proud of what you have achieved in ~6 weeks.
- Consider taking actions from previous week review (create milestones for each sprint).
- Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place.
- Good to see you have tasks/issues being worked on actively. 
- You guys should start adding more UI polish to your app
- Good to see that your team had regular commits/pull-requests to merge the code
- Consider improving your test coverage by incorporating positive as well as negative testing to determine if your app handles improper user behavior correctly.
- Keep working on integrating the core flows and make sure all pieces fit together perfectly.
- Consult with your mentors to get their feedback as often as you can. Remember they are here to help!
- While working on polishing your app for next sprint, remember that your app follows the [android design guidelines](http://guides.codepath.com/android/Android-Design-Guidelines) and also benchmark your app on sites such as [android app patterns](http://www.android-app-patterns.com/) to improve the UI/UX.

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week!
